# Generated by Django 3.0 on 2019-12-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno', '0002_auto_20191217_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='train',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_class',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='cut_points',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
