# Generated by Django 3.0 on 2019-12-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno', '0005_auto_20191218_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='prev_vid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
