# Generated by Django 3.0 on 2019-12-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno', '0006_video_prev_vid'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='certainty',
            field=models.BooleanField(default=True),
        ),
    ]
