# Generated by Django 3.0 on 2019-12-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno', '0007_video_certainty'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='note',
            field=models.CharField(default='', max_length=300),
        ),
    ]
