# Generated by Django 3.0 on 2020-01-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno', '0008_video_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='certainty',
            field=models.BooleanField(choices=[(0, 'UNCERTAIN'), (1, 'CERTAIN')], default=True),
        ),
    ]
