# Generated by Django 3.0 on 2020-02-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=60)),
                ('choices', models.CharField(max_length=720)),
                ('answers', models.CharField(default='', max_length=20)),
                ('answerers', models.CharField(max_length=320)),
                ('correct_answer', models.PositiveSmallIntegerField(default=5)),
                ('phase', models.CharField(default='test', max_length=10)),
                ('setting', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
