# Generated by Django 3.0 on 2020-02-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humantest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionAnswer',
            new_name='QA',
        ),
    ]
